# Generated by Django 2.2 on 2021-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_singroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='votes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
